default:
  font: Helvetica
  bold: "{* Bold}"
  mono: Andale Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "Thank you for using TDM and reading this book."